---
- name: Modern Server
  hosts: all
  any_errors_fatal: true
  roles:
    - jdk8
    - gradle
    - role: mysql
      mysql:
        database: modern
        user: colin
        password: truth
    - xserver

- name: Modern CI
  hosts: modern_ci_servers
  any_errors_fatal: true
  roles:
    - jenkins