---
- name: Modern Server
  hosts: all
  vars_files:
    - src/main/resources/application.yml
  any_errors_fatal: true
  roles:
    - jdk8
    - gradle
    - role: mysql
      mysql:
        database: moderntest
        user: "{{ spring.datasource.username }}"
        password: "{{ spring.datasource.password }}"
    - role: mysql
      mysql:
        database: moderndev
        user: "{{ spring.datasource.username }}"
        password: "{{ spring.datasource.password }}"
    - firefox

- name: Modern CI
  hosts: modern_ci_servers
  any_errors_fatal: true
  roles:
    - role: jenkins
      jenkins:
        port: 8000