---
- name: Modern Server
  hosts: all
  any_errors_fatal: true
  roles:
    - jdk8
    - gradle
    - role: mysql
      mysql:
        database: moderntest
        user: colin
        password: truth
    - firefox

- name: Modern CI
  hosts: modern_ci_servers
  any_errors_fatal: true
  roles:
    - role: jenkins
      jenkins:
        port: 8000