- name: Gradle | Ensure cache directory
  file: path="{{ gradle.cache_dir }}" state=directory

- name: Gradle | Download gradle
  get_url:
    url: "https://services.gradle.org/distributions/gradle-{{gradle.version}}-all.zip"
    dest: "{{ gradle.cache_dir }}/gradle-{{ gradle.version }}-all.zip"

- name: Gradle | apt-get update
  apt: update_cache=yes cache_valid_time=604800

- name: Gradle | Install unzip
  apt: pkg=unzip state=latest
  when: ansible_os_family == "Debian"

- name: Gradle | Unpack the compress Gradle
  shell: |
    mkdir -p "{{ gradle.install_to }}"
    unzip "{{ gradle.cache_dir }}/gradle-{{ gradle.version }}-all.zip" -d "{{ gradle.install_to }}"
  args:
    creates: "{{ gradle.install_to }}/gradle-{{ gradle.version }}"

- name: Gradle | Add the Gradle binary to the system path
  copy:
    dest: "{{ gradle.profile }}"
    content: |
      export GRADLE_HOME="{{ gradle.install_to }}/gradle-{{ gradle.version }}"
      export PATH="$GRADLE_HOME/bin:$PATH"
  when: ansible_os_family == "Debian"