spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moderntest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080

