spring:
  datasource:
    username: colin
    password: truth
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  messages:
    basename: BindingErrorMessages

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/moderndev?createDatabaseIfNotExist=true&useSSL=false

server:
  port: 8090

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/moderntest?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080

