- block:
  - name: Ensure mysql server
    apt: name="{{ item }}"
    with_items:
      - mysql-server
      - python-mysqldb
  when: ansible_os_family == "Debian"

- name: Ensure mysql database
  mysql_db: name="{{ mysql.database }}" state=present
