- block:
  - name: Adding the ke for Jenkins repository
    apt_key: url=http://pkg.jenkins-ci.org/debian-stable/jenkins.io.key

  - name: Adding Jekins source
    copy:
      dest: /etc/apt/sources.list.d/jekins.list
      content: |
        deb http://pkg.jenkins.io/debian-stable binary/
    register: jenkins_source

  - name: Update apt cache
    apt: update_cache=yes
    when: jenkins_source | changed

  - name: Ensure Jenkins
    apt: name=jenkins update_cache=yes cache_valid_time=604800

  - name: Changing Jenkins http port
    lineinfile: name=/etc/default/jenkins regexp="^HTTP_PORT=.+" line="HTTP_PORT={{ jenkins.port | default('8080') }}"

  when: ansible_os_family == "Debian"